name: Grant Application
description: Apply for a grant

title: "Awesome Project Name"
labels: ["grant", "application"]
assignees:
  - dantaik
  - d1onys1us
  - 2manslkh
  - MarcusWentz
  - mfinestone

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in applying for a grant! Please fill out the following information:

  - type: textarea
    id: project_description
    attributes:
      label: Project Description
      description: Provide a brief description of your project and its objectives
      placeholder: |
        This project aims to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best fits your project
      options:
        - Zero-Knowledge Proofs (ZKP)
        - Proposer Optimization
        - Alternative Proposer-Prover Tokenomics
        - Proof Markets
        - Social/Messaging dApps
        - NFT Bridge & Marketplace
        - Games
        - AI Integration
        - Surprise 🤫
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: |
        Outline the estimated timeline for your project, including key milestones and deliverables.
        A project’s timeline for completion should be no longer than 6 months. It can be shorter than 6 months. Projects that require more time may find fit with alternative programs we roll out.
      placeholder: |
        [DATE]: [MILESTONE]
        e.g.
        1 July 2023: Deploy on testnet
        1 September 2023: Audit all smart contracts
        1 November 2023: Deploy on mainnet
    validations:
      required: true

  - type: textarea
    id: project_plan
    attributes:
      label: Project Plan
      description: Describe your project plan and how you intend to achieve your goals. Include any relevant details such as methodologies, technologies, or resources required
      placeholder: |
        We will build a... using...
    validations:
      required: true

  - type: textarea
    id: project_impact
    attributes:
      label: Project Impact
      description: Explain the potential impact of your project. How will it benefit the community or target audience? What problem does it address?
      placeholder: |
        Users will be able to... which will...
    validations:
      required: true

  - type: textarea
    id: budget_breakdown
    attributes:
      label: Budget Breakdown
      description: Provide a breakdown of how the funding will be allocated. List the major expense categories and their respective amounts

  - type: textarea
    id: team_information
    attributes:
      label: Team Information
      description: Introduce your project team and provide a brief overview of their relevant skills and experience
      placeholder: |
        Alice: Project Lead
        - 5 years of experience in...
        Bob: Developer
        - 3 years of experience in...
        Charlie: Designer
        - 2 years of experience in...
    validations:
      required: true

  - type: input
    id: point_of_contact
    attributes:
      label: Point of Contact
      description: Let us know how we may contact you
      placeholder: |
        tg: @zkenk | discord: zKenk | email: keng@taiko.xyz
    validations:
      required: true

  - type: textarea
    id: previous_work
    attributes:
      label: Previous Work
      description: If applicable, share any previous work or achievements that demonstrate your team's capabilities or progress related to the project
    validations:
      required: false

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Include any additional information or supporting documents that you think would be helpful in evaluating your grant application
    validations:
      required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: Agreement
      description: |
        By submitting this grant application, you agree to comply with the terms and conditions of the grants program.

        1. Grantees and Taiko Labs will establish and sign an agreement detailing the expectations and responsibilities of both parties.
        2. Before execution of the agreement, discretion for changes in the program rest exclusively with Taiko Labs.
        3. Taiko Labs or its associated entities receive priority to invest up to $250K USD in a subsequent funding round if the project fundraises within one year post-grant acceptance.
        4. Grantees can apply for grants from other projects, given all other requirements are met.
        5. Projects involving dApps must choose Taiko as one of their very first platforms, but they can also deploy elsewhere if they see fit. We do look favourably upon Taiko-tailored projects: those that truly take advantage of Taiko’s strengths and design decisions, such as Ethereum-equivalence and permissionless proposing and proving. 
        6. Unless explicitly stated otherwise, all code should be open-sourced from the project's inception.

      options:
        - label: I agree to comply with the terms and conditions of the grants program
          required: true
