name: Grant Application
description: Apply for a grant

title: "[Grant Application]: "
labels: ["grant", "application"]
assignees:
  - dantaik
  - d1onys1us
  - 2manslkh
  - MarcusWentz
  - mfinestone

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in applying for a grant! Please fill out the following information:

  - type: input
    id: project_title
    attributes:
      label: Project Title
      description: Provide a title for your project
      placeholder: |
        Awesome Taiko Project
    validations:
      required: true

  - type: textarea
    id: project_description
    attributes:
      label: Project Description
      description: Provide a brief description of your project and its objectives
      placeholder: |
        This project aims to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best fits your project
      options:
        - Zero-Knowledge Proofs (ZKP)
        - Proposer Optimization
        - Alternative Proposer-Prover Tokenomics
        - Proof Markets
        - Social/Messaging dApps
        - NFT Bridge & Marketplace
        - Games
        - AI Integration
        - Surprise 🤫
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: |
        Outline the estimated timeline for your project, including key milestones and deliverables.
        A project’s timeline for completion should be no longer than 6 months. It can be shorter than 6 months. Projects that require more time may find fit with alternative programs we roll out.
      placeholder: |
        [DATE]: [MILESTONE]
        e.g.
        1 July 2023: Deploy on testnet
        1 September 2023: Audit all smart contracts
        1 November 2023: Deploy on mainnet
    validations:
      required: true

  - type: textarea
    id: project_plan
    attributes:
      label: Project Plan
      description: Describe your project plan and how you intend to achieve your goals. Include any relevant details such as methodologies, technologies, or resources required
      placeholder: |
        We will build a... using...
    validations:
      required: true

  - type: textarea
    id: project_impact
    attributes:
      label: Project Impact
      description: Explain the potential impact of your project. How will it benefit the community or target audience? What problem does it address?
      placeholder: |
        Users will be able to... which will...
    validations:
      required: true

  - type: textarea
    id: budget_breakdown
    attributes:
      label: Budget Breakdown
      description: Provide a breakdown of how the funding will be allocated. List the major expense categories and their respective amounts

  - type: textarea
    id: team_information
    attributes:
      label: Team Information
      description: Introduce your project team and provide a brief overview of their relevant skills and experience
      placeholder: |
        Alice: Project Lead
        - 5 years of experience in...
        Bob: Developer
        - 3 years of experience in...
        Charlie: Designer
        - 2 years of experience in...
    validations:
      required: true

  - type: input
    id: point_of_contact
    attributes:
      label: Point of Contact
      description: Let us know how we may contact you
      placeholder: |
        tg: @zkenk | discord: zKenk | email: keng@taiko.xyz
    validations:
      required: true

  - type: textarea
    id: previous_work
    attributes:
      label: Previous Work
      description: If applicable, share any previous work or achievements that demonstrate your team's capabilities or progress related to the project
    validations:
      required: false

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Include any additional information or supporting documents that you think would be helpful in evaluating your grant application
    validations:
      required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: Agreement
      description: By submitting this grant application, you agree to comply with the terms and conditions of the grants program
      options:
        - label: I agree to comply with the terms and conditions of the grants program
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
